# Form implementation generated from reading ui file 'ui/add_music_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_qDialog_addMusicDialog(object):
    def setupUi(self, qDialog_addMusicDialog):
        qDialog_addMusicDialog.setObjectName("qDialog_addMusicDialog")
        qDialog_addMusicDialog.resize(450, 113)
        self.verticalLayout = QtWidgets.QVBoxLayout(qDialog_addMusicDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=qDialog_addMusicDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.qComboBox_selectFromData = QtWidgets.QComboBox(parent=qDialog_addMusicDialog)
        self.qComboBox_selectFromData.setObjectName("qComboBox_selectFromData")
        self.horizontalLayout.addWidget(self.qComboBox_selectFromData)
        self.qPushButton_add_from_data = QtWidgets.QPushButton(parent=qDialog_addMusicDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qPushButton_add_from_data.sizePolicy().hasHeightForWidth())
        self.qPushButton_add_from_data.setSizePolicy(sizePolicy)
        self.qPushButton_add_from_data.setObjectName("qPushButton_add_from_data")
        self.horizontalLayout.addWidget(self.qPushButton_add_from_data)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.qPushButton_open_downloader = QtWidgets.QPushButton(parent=qDialog_addMusicDialog)
        self.qPushButton_open_downloader.setObjectName("qPushButton_open_downloader")
        self.verticalLayout.addWidget(self.qPushButton_open_downloader)
        self.qPushButton_quit = QtWidgets.QPushButton(parent=qDialog_addMusicDialog)
        self.qPushButton_quit.setObjectName("qPushButton_quit")
        self.verticalLayout.addWidget(self.qPushButton_quit)

        self.retranslateUi(qDialog_addMusicDialog)
        QtCore.QMetaObject.connectSlotsByName(qDialog_addMusicDialog)

    def retranslateUi(self, qDialog_addMusicDialog):
        _translate = QtCore.QCoreApplication.translate
        qDialog_addMusicDialog.setWindowTitle(_translate("qDialog_addMusicDialog", "Easy Music Plus Add Music"))
        self.label.setText(_translate("qDialog_addMusicDialog", "选择已有歌曲"))
        self.qPushButton_add_from_data.setText(_translate("qDialog_addMusicDialog", "添加"))
        self.qPushButton_open_downloader.setText(_translate("qDialog_addMusicDialog", "下载新歌曲"))
        self.qPushButton_quit.setText(_translate("qDialog_addMusicDialog", "关闭"))
