# Form implementation generated from reading ui file 'ui/about_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_qDialog_aboutDialog(object):
    def setupUi(self, qDialog_aboutDialog):
        qDialog_aboutDialog.setObjectName("qDialog_aboutDialog")
        qDialog_aboutDialog.resize(701, 607)
        self.verticalLayout = QtWidgets.QVBoxLayout(qDialog_aboutDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.qTextBrowser_about = QtWidgets.QTextBrowser(parent=qDialog_aboutDialog)
        self.qTextBrowser_about.setObjectName("qTextBrowser_about")
        self.verticalLayout.addWidget(self.qTextBrowser_about)
        self.qPushButton_quit = QtWidgets.QPushButton(parent=qDialog_aboutDialog)
        self.qPushButton_quit.setObjectName("qPushButton_quit")
        self.verticalLayout.addWidget(self.qPushButton_quit)

        self.retranslateUi(qDialog_aboutDialog)
        QtCore.QMetaObject.connectSlotsByName(qDialog_aboutDialog)

    def retranslateUi(self, qDialog_aboutDialog):
        _translate = QtCore.QCoreApplication.translate
        qDialog_aboutDialog.setWindowTitle(_translate("qDialog_aboutDialog", "About Easy Music Plus"))
        self.qTextBrowser_about.setHtml(_translate("qDialog_aboutDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:600;\">Easy Music Plus</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">By shicj</p>\n"
"<hr />\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Easy Music Plus 是一个基于 Python 与 Qt 开发的跨平台音视频工具，用于音视频信息获取、播放与下载管理。</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">本软件仅供学习、研究与个人使用，请遵守相关法律法规以及各平台的用户协议与版权要求。用户应自行承担因使用本软件产生的相关责任。</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">本软件为开源/非商业项目，不隶属于任何音乐、视频或内容平台。</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">使用的主要开源组件：</p>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\">\n"
"<li style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Qt / PyQt</li>\n"
"<li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Python</li>\n"
"<li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">yt-dlp</li>\n"
"<li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">FFmpeg</li>\n"
"<li style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">requests</li></ul>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">第三方组件版权归其各自作者与组织所有。</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Qt 使用 LGPLv3/GPLv3 开源许可。本软件通过动态链接方式使用 Qt，并遵循对应开源协议要求。用户可自行替换 Qt 动态库版本。</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">FFmpeg 为独立开源项目，其版权与许可协议归 FFmpeg 项目所有。</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">yt-dlp 为独立开源项目，遵循其官方许可证发布。</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">本软件不提供、不存储任何音视频内容，所有内容均来自用户主动访问的第三方平台。</p>\n"
"<hr />\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">© 2026 shicj</p></body></html>"))
        self.qPushButton_quit.setText(_translate("qDialog_aboutDialog", "关闭"))
