# Form implementation generated from reading ui file 'ui/add_music_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_qDialog_addMusicDialog(object):
    def setupUi(self, qDialog_addMusicDialog):
        qDialog_addMusicDialog.setObjectName("qDialog_addMusicDialog")
        qDialog_addMusicDialog.resize(450, 140)
        self.verticalLayout = QtWidgets.QVBoxLayout(qDialog_addMusicDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.qPushButton_add_from_list = QtWidgets.QPushButton(parent=qDialog_addMusicDialog)
        self.qPushButton_add_from_list.setObjectName("qPushButton_add_from_list")
        self.verticalLayout.addWidget(self.qPushButton_add_from_list)
        self.qPushButton_open_downloader = QtWidgets.QPushButton(parent=qDialog_addMusicDialog)
        self.qPushButton_open_downloader.setObjectName("qPushButton_open_downloader")
        self.verticalLayout.addWidget(self.qPushButton_open_downloader)
        self.qPushButton_netease_songlist = QtWidgets.QPushButton(parent=qDialog_addMusicDialog)
        self.qPushButton_netease_songlist.setObjectName("qPushButton_netease_songlist")
        self.verticalLayout.addWidget(self.qPushButton_netease_songlist)
        self.qPushButton_quit = QtWidgets.QPushButton(parent=qDialog_addMusicDialog)
        self.qPushButton_quit.setObjectName("qPushButton_quit")
        self.verticalLayout.addWidget(self.qPushButton_quit)

        self.retranslateUi(qDialog_addMusicDialog)
        QtCore.QMetaObject.connectSlotsByName(qDialog_addMusicDialog)

    def retranslateUi(self, qDialog_addMusicDialog):
        _translate = QtCore.QCoreApplication.translate
        qDialog_addMusicDialog.setWindowTitle(_translate("qDialog_addMusicDialog", "Easy Music Plus Add Music"))
        self.qPushButton_add_from_list.setText(_translate("qDialog_addMusicDialog", "从已有歌曲/歌单添加"))
        self.qPushButton_open_downloader.setText(_translate("qDialog_addMusicDialog", "下载新歌曲（网易云/bilibili）"))
        self.qPushButton_netease_songlist.setText(_translate("qDialog_addMusicDialog", "爬取网易云音乐歌单"))
        self.qPushButton_quit.setText(_translate("qDialog_addMusicDialog", "关闭"))
