# Form implementation generated from reading ui file 'ui/add_music_from_list_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_qDialog_addMusicFromListDialog(object):
    def setupUi(self, qDialog_addMusicFromListDialog):
        qDialog_addMusicFromListDialog.setObjectName("qDialog_addMusicFromListDialog")
        qDialog_addMusicFromListDialog.resize(400, 568)
        self.verticalLayout = QtWidgets.QVBoxLayout(qDialog_addMusicFromListDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.qLineEdit_search = QtWidgets.QLineEdit(parent=qDialog_addMusicFromListDialog)
        self.qLineEdit_search.setInputMask("")
        self.qLineEdit_search.setObjectName("qLineEdit_search")
        self.verticalLayout.addWidget(self.qLineEdit_search)
        self.qTreeWidget_songs = QtWidgets.QTreeWidget(parent=qDialog_addMusicFromListDialog)
        self.qTreeWidget_songs.setObjectName("qTreeWidget_songs")
        self.qTreeWidget_songs.headerItem().setText(0, "1")
        self.verticalLayout.addWidget(self.qTreeWidget_songs)
        self.qPushButton_add = QtWidgets.QPushButton(parent=qDialog_addMusicFromListDialog)
        self.qPushButton_add.setObjectName("qPushButton_add")
        self.verticalLayout.addWidget(self.qPushButton_add)
        self.qPushButton_quit = QtWidgets.QPushButton(parent=qDialog_addMusicFromListDialog)
        self.qPushButton_quit.setObjectName("qPushButton_quit")
        self.verticalLayout.addWidget(self.qPushButton_quit)

        self.retranslateUi(qDialog_addMusicFromListDialog)
        QtCore.QMetaObject.connectSlotsByName(qDialog_addMusicFromListDialog)

    def retranslateUi(self, qDialog_addMusicFromListDialog):
        _translate = QtCore.QCoreApplication.translate
        qDialog_addMusicFromListDialog.setWindowTitle(_translate("qDialog_addMusicFromListDialog", "Easy Music Plus Add Music From List"))
        self.qLineEdit_search.setPlaceholderText(_translate("qDialog_addMusicFromListDialog", "搜索"))
        self.qPushButton_add.setText(_translate("qDialog_addMusicFromListDialog", "添加"))
        self.qPushButton_quit.setText(_translate("qDialog_addMusicFromListDialog", "取消"))
