# Form implementation generated from reading ui file 'ui/get_netease_songlist_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_qDialog_get_netease_songlist(object):
    def setupUi(self, qDialog_get_netease_songlist):
        qDialog_get_netease_songlist.setObjectName("qDialog_get_netease_songlist")
        qDialog_get_netease_songlist.resize(648, 469)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(qDialog_get_netease_songlist)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.qLabel_songlist_name = QtWidgets.QLabel(parent=qDialog_get_netease_songlist)
        self.qLabel_songlist_name.setObjectName("qLabel_songlist_name")
        self.horizontalLayout.addWidget(self.qLabel_songlist_name)
        self.qLineEdit_id = QtWidgets.QLineEdit(parent=qDialog_get_netease_songlist)
        self.qLineEdit_id.setText("")
        self.qLineEdit_id.setObjectName("qLineEdit_id")
        self.horizontalLayout.addWidget(self.qLineEdit_id)
        self.qPushButton_get_ids = QtWidgets.QPushButton(parent=qDialog_get_netease_songlist)
        self.qPushButton_get_ids.setObjectName("qPushButton_get_ids")
        self.horizontalLayout.addWidget(self.qPushButton_get_ids)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.qLabel_song_ids = QtWidgets.QLabel(parent=qDialog_get_netease_songlist)
        self.qLabel_song_ids.setObjectName("qLabel_song_ids")
        self.verticalLayout.addWidget(self.qLabel_song_ids)
        self.qPlainTextEdit_song_ids = QtWidgets.QPlainTextEdit(parent=qDialog_get_netease_songlist)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qPlainTextEdit_song_ids.sizePolicy().hasHeightForWidth())
        self.qPlainTextEdit_song_ids.setSizePolicy(sizePolicy)
        self.qPlainTextEdit_song_ids.setMaximumSize(QtCore.QSize(100, 16777215))
        self.qPlainTextEdit_song_ids.setObjectName("qPlainTextEdit_song_ids")
        self.verticalLayout.addWidget(self.qPlainTextEdit_song_ids)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.qPlainTextEdit_log = QtWidgets.QPlainTextEdit(parent=qDialog_get_netease_songlist)
        self.qPlainTextEdit_log.setReadOnly(True)
        self.qPlainTextEdit_log.setObjectName("qPlainTextEdit_log")
        self.horizontalLayout_2.addWidget(self.qPlainTextEdit_log)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.qProgressBar_progress = QtWidgets.QProgressBar(parent=qDialog_get_netease_songlist)
        self.qProgressBar_progress.setProperty("value", 0)
        self.qProgressBar_progress.setObjectName("qProgressBar_progress")
        self.verticalLayout_2.addWidget(self.qProgressBar_progress)
        self.qPushButton_start = QtWidgets.QPushButton(parent=qDialog_get_netease_songlist)
        self.qPushButton_start.setObjectName("qPushButton_start")
        self.verticalLayout_2.addWidget(self.qPushButton_start)
        self.qPushButton_quit = QtWidgets.QPushButton(parent=qDialog_get_netease_songlist)
        self.qPushButton_quit.setObjectName("qPushButton_quit")
        self.verticalLayout_2.addWidget(self.qPushButton_quit)

        self.retranslateUi(qDialog_get_netease_songlist)
        QtCore.QMetaObject.connectSlotsByName(qDialog_get_netease_songlist)

    def retranslateUi(self, qDialog_get_netease_songlist):
        _translate = QtCore.QCoreApplication.translate
        qDialog_get_netease_songlist.setWindowTitle(_translate("qDialog_get_netease_songlist", "Easy Music Plus Get Netease Songlist"))
        self.qLabel_songlist_name.setText(_translate("qDialog_get_netease_songlist", "歌单id"))
        self.qPushButton_get_ids.setText(_translate("qDialog_get_netease_songlist", "加载"))
        self.qLabel_song_ids.setText(_translate("qDialog_get_netease_songlist", "一行一个歌曲id"))
        self.qPushButton_start.setText(_translate("qDialog_get_netease_songlist", "开始下载"))
        self.qPushButton_quit.setText(_translate("qDialog_get_netease_songlist", "退出"))
