# Form implementation generated from reading ui file 'ui/get_netease_songlist_id_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_qDialog_getNeteaseSonglistId(object):
    def setupUi(self, qDialog_getNeteaseSonglistId):
        qDialog_getNeteaseSonglistId.setObjectName("qDialog_getNeteaseSonglistId")
        qDialog_getNeteaseSonglistId.resize(400, 260)
        self.verticalLayout = QtWidgets.QVBoxLayout(qDialog_getNeteaseSonglistId)
        self.verticalLayout.setObjectName("verticalLayout")
        self.qTextBrowser_tips = QtWidgets.QTextBrowser(parent=qDialog_getNeteaseSonglistId)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qTextBrowser_tips.sizePolicy().hasHeightForWidth())
        self.qTextBrowser_tips.setSizePolicy(sizePolicy)
        self.qTextBrowser_tips.setMinimumSize(QtCore.QSize(0, 100))
        self.qTextBrowser_tips.setObjectName("qTextBrowser_tips")
        self.verticalLayout.addWidget(self.qTextBrowser_tips)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.qLabel_songlistId = QtWidgets.QLabel(parent=qDialog_getNeteaseSonglistId)
        self.qLabel_songlistId.setObjectName("qLabel_songlistId")
        self.horizontalLayout.addWidget(self.qLabel_songlistId)
        self.qLineEdit_songlistId = QtWidgets.QLineEdit(parent=qDialog_getNeteaseSonglistId)
        self.qLineEdit_songlistId.setObjectName("qLineEdit_songlistId")
        self.horizontalLayout.addWidget(self.qLineEdit_songlistId)
        self.qPushButton_getSonglist = QtWidgets.QPushButton(parent=qDialog_getNeteaseSonglistId)
        self.qPushButton_getSonglist.setObjectName("qPushButton_getSonglist")
        self.horizontalLayout.addWidget(self.qPushButton_getSonglist)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.qPlainTextEdit_log = QtWidgets.QPlainTextEdit(parent=qDialog_getNeteaseSonglistId)
        self.qPlainTextEdit_log.setReadOnly(True)
        self.qPlainTextEdit_log.setObjectName("qPlainTextEdit_log")
        self.verticalLayout.addWidget(self.qPlainTextEdit_log)
        self.qPushButton_quit = QtWidgets.QPushButton(parent=qDialog_getNeteaseSonglistId)
        self.qPushButton_quit.setObjectName("qPushButton_quit")
        self.verticalLayout.addWidget(self.qPushButton_quit)

        self.retranslateUi(qDialog_getNeteaseSonglistId)
        QtCore.QMetaObject.connectSlotsByName(qDialog_getNeteaseSonglistId)

    def retranslateUi(self, qDialog_getNeteaseSonglistId):
        _translate = QtCore.QCoreApplication.translate
        qDialog_getNeteaseSonglistId.setWindowTitle(_translate("qDialog_getNeteaseSonglistId", "Easy Music Plus Get Songlist ID"))
        self.qTextBrowser_tips.setHtml(_translate("qDialog_getNeteaseSonglistId", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">从网易云客户端爬取歌单路径：</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1. 带调试选项（--remote-debugging-port=9999  --remote-allow-origins=*）开启客户端进程</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2. 输入调试地址（http://127.0.0.1:9999）</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">3. 点击“加载”获取信息</p></body></html>"))
        self.qLabel_songlistId.setText(_translate("qDialog_getNeteaseSonglistId", "调试地址："))
        self.qPushButton_getSonglist.setText(_translate("qDialog_getNeteaseSonglistId", "加载"))
        self.qPushButton_quit.setText(_translate("qDialog_getNeteaseSonglistId", "退出"))
