# Form implementation generated from reading ui file 'ui/get_netease_songlist_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_qDialog_get_netease_songlist(object):
    def setupUi(self, qDialog_get_netease_songlist):
        qDialog_get_netease_songlist.setObjectName("qDialog_get_netease_songlist")
        qDialog_get_netease_songlist.resize(648, 469)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(qDialog_get_netease_songlist)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.qTextBrowser_help = QtWidgets.QTextBrowser(parent=qDialog_get_netease_songlist)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qTextBrowser_help.sizePolicy().hasHeightForWidth())
        self.qTextBrowser_help.setSizePolicy(sizePolicy)
        self.qTextBrowser_help.setMinimumSize(QtCore.QSize(230, 270))
        self.qTextBrowser_help.setObjectName("qTextBrowser_help")
        self.horizontalLayout_2.addWidget(self.qTextBrowser_help)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.qLabel_songlist_name = QtWidgets.QLabel(parent=qDialog_get_netease_songlist)
        self.qLabel_songlist_name.setObjectName("qLabel_songlist_name")
        self.horizontalLayout.addWidget(self.qLabel_songlist_name)
        self.qLineEdit_url = QtWidgets.QLineEdit(parent=qDialog_get_netease_songlist)
        self.qLineEdit_url.setObjectName("qLineEdit_url")
        self.horizontalLayout.addWidget(self.qLineEdit_url)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.qPushButton_request = QtWidgets.QPushButton(parent=qDialog_get_netease_songlist)
        self.qPushButton_request.setObjectName("qPushButton_request")
        self.verticalLayout_2.addWidget(self.qPushButton_request)
        self.qPlainTextEdit_get_log = QtWidgets.QPlainTextEdit(parent=qDialog_get_netease_songlist)
        self.qPlainTextEdit_get_log.setReadOnly(True)
        self.qPlainTextEdit_get_log.setObjectName("qPlainTextEdit_get_log")
        self.verticalLayout_2.addWidget(self.qPlainTextEdit_get_log)
        self.qPushButton_get_ids = QtWidgets.QPushButton(parent=qDialog_get_netease_songlist)
        self.qPushButton_get_ids.setObjectName("qPushButton_get_ids")
        self.verticalLayout_2.addWidget(self.qPushButton_get_ids)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.qLabel_song_ids = QtWidgets.QLabel(parent=qDialog_get_netease_songlist)
        self.qLabel_song_ids.setObjectName("qLabel_song_ids")
        self.verticalLayout.addWidget(self.qLabel_song_ids)
        self.qPlainTextEdit_song_ids = QtWidgets.QPlainTextEdit(parent=qDialog_get_netease_songlist)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qPlainTextEdit_song_ids.sizePolicy().hasHeightForWidth())
        self.qPlainTextEdit_song_ids.setSizePolicy(sizePolicy)
        self.qPlainTextEdit_song_ids.setMaximumSize(QtCore.QSize(100, 16777215))
        self.qPlainTextEdit_song_ids.setObjectName("qPlainTextEdit_song_ids")
        self.verticalLayout.addWidget(self.qPlainTextEdit_song_ids)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.qPushButton_start = QtWidgets.QPushButton(parent=qDialog_get_netease_songlist)
        self.qPushButton_start.setObjectName("qPushButton_start")
        self.verticalLayout_3.addWidget(self.qPushButton_start)
        self.qPushButton_quit = QtWidgets.QPushButton(parent=qDialog_get_netease_songlist)
        self.qPushButton_quit.setObjectName("qPushButton_quit")
        self.verticalLayout_3.addWidget(self.qPushButton_quit)
        self.qPlainTextEdit_log = QtWidgets.QPlainTextEdit(parent=qDialog_get_netease_songlist)
        self.qPlainTextEdit_log.setReadOnly(True)
        self.qPlainTextEdit_log.setObjectName("qPlainTextEdit_log")
        self.verticalLayout_3.addWidget(self.qPlainTextEdit_log)
        self.qProgressBar_progress = QtWidgets.QProgressBar(parent=qDialog_get_netease_songlist)
        self.qProgressBar_progress.setProperty("value", 0)
        self.qProgressBar_progress.setObjectName("qProgressBar_progress")
        self.verticalLayout_3.addWidget(self.qProgressBar_progress)

        self.retranslateUi(qDialog_get_netease_songlist)
        QtCore.QMetaObject.connectSlotsByName(qDialog_get_netease_songlist)

    def retranslateUi(self, qDialog_get_netease_songlist):
        _translate = QtCore.QCoreApplication.translate
        qDialog_get_netease_songlist.setWindowTitle(_translate("qDialog_get_netease_songlist", "Easy Music Plus Get Netease Songlist"))
        self.qTextBrowser_help.setHtml(_translate("qDialog_get_netease_songlist", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">使用自动获取歌单功能：</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1. 关闭客户端，使用 <span style=\" font-style:italic;\">cloudmusic.exe --remote-debugging-port=9222</span> 开启新进程</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2. 填写连接地址，在本机调试则保留 <span style=\" font-style:italic;\">http://127.0.0.1:9222</span> 不变</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">3. 在客户端打开歌单</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">4. 点击“获取”按钮，尝试加载歌单</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">5. 点击“加载”按钮，内容自动填充到右侧输入框</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">注意：此功能稳定性/合规性没有保证，不建议在登录状态使用，如果失败可以尝试重试或更换客户端版本</span></p></body></html>"))
        self.qLabel_songlist_name.setText(_translate("qDialog_get_netease_songlist", "连接地址"))
        self.qLineEdit_url.setText(_translate("qDialog_get_netease_songlist", "http://192.168.3.40:9223"))
        self.qPushButton_request.setText(_translate("qDialog_get_netease_songlist", "获取"))
        self.qPushButton_get_ids.setText(_translate("qDialog_get_netease_songlist", "加载"))
        self.qLabel_song_ids.setText(_translate("qDialog_get_netease_songlist", "一行一个歌曲id"))
        self.qPushButton_start.setText(_translate("qDialog_get_netease_songlist", "开始下载"))
        self.qPushButton_quit.setText(_translate("qDialog_get_netease_songlist", "退出"))
