# Form implementation generated from reading ui file 'ui/search_lyric_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_qDialog_searchLyricDialog(object):
    def setupUi(self, qDialog_searchLyricDialog):
        qDialog_searchLyricDialog.setObjectName("qDialog_searchLyricDialog")
        qDialog_searchLyricDialog.resize(400, 568)
        self.verticalLayout = QtWidgets.QVBoxLayout(qDialog_searchLyricDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.qLineEdit_search = QtWidgets.QLineEdit(parent=qDialog_searchLyricDialog)
        self.qLineEdit_search.setObjectName("qLineEdit_search")
        self.horizontalLayout.addWidget(self.qLineEdit_search)
        self.qPushButton_search = QtWidgets.QPushButton(parent=qDialog_searchLyricDialog)
        self.qPushButton_search.setObjectName("qPushButton_search")
        self.horizontalLayout.addWidget(self.qPushButton_search)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.qTreeWidget_lyric = QtWidgets.QTreeWidget(parent=qDialog_searchLyricDialog)
        self.qTreeWidget_lyric.setObjectName("qTreeWidget_lyric")
        self.qTreeWidget_lyric.headerItem().setText(0, "1")
        self.verticalLayout.addWidget(self.qTreeWidget_lyric)
        self.qProgressBar = QtWidgets.QProgressBar(parent=qDialog_searchLyricDialog)
        self.qProgressBar.setProperty("value", 0)
        self.qProgressBar.setObjectName("qProgressBar")
        self.verticalLayout.addWidget(self.qProgressBar)
        self.qPushButton_quit = QtWidgets.QPushButton(parent=qDialog_searchLyricDialog)
        self.qPushButton_quit.setObjectName("qPushButton_quit")
        self.verticalLayout.addWidget(self.qPushButton_quit)

        self.retranslateUi(qDialog_searchLyricDialog)
        QtCore.QMetaObject.connectSlotsByName(qDialog_searchLyricDialog)

    def retranslateUi(self, qDialog_searchLyricDialog):
        _translate = QtCore.QCoreApplication.translate
        qDialog_searchLyricDialog.setWindowTitle(_translate("qDialog_searchLyricDialog", "Easy Music Plus Search Lyric"))
        self.qLineEdit_search.setPlaceholderText(_translate("qDialog_searchLyricDialog", "搜索"))
        self.qPushButton_search.setText(_translate("qDialog_searchLyricDialog", "搜索"))
        self.qPushButton_quit.setText(_translate("qDialog_searchLyricDialog", "退出"))
