# Form implementation generated from reading ui file 'ui/search_lyric_online_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_qDialog_search_lyric(object):
    def setupUi(self, qDialog_search_lyric):
        qDialog_search_lyric.setObjectName("qDialog_search_lyric")
        qDialog_search_lyric.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(qDialog_search_lyric)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.qComboBox_source = QtWidgets.QComboBox(parent=qDialog_search_lyric)
        self.qComboBox_source.setObjectName("qComboBox_source")
        self.qComboBox_source.addItem("")
        self.qComboBox_source.addItem("")
        self.qComboBox_source.addItem("")
        self.horizontalLayout_2.addWidget(self.qComboBox_source)
        self.qLineEdit = QtWidgets.QLineEdit(parent=qDialog_search_lyric)
        self.qLineEdit.setObjectName("qLineEdit")
        self.horizontalLayout_2.addWidget(self.qLineEdit)
        self.qPushButton_search = QtWidgets.QPushButton(parent=qDialog_search_lyric)
        self.qPushButton_search.setObjectName("qPushButton_search")
        self.horizontalLayout_2.addWidget(self.qPushButton_search)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.qTreeWidget = QtWidgets.QTreeWidget(parent=qDialog_search_lyric)
        self.qTreeWidget.setObjectName("qTreeWidget")
        self.qTreeWidget.headerItem().setText(0, "1")
        self.horizontalLayout.addWidget(self.qTreeWidget)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.qPushButton_submit = QtWidgets.QPushButton(parent=qDialog_search_lyric)
        self.qPushButton_submit.setObjectName("qPushButton_submit")
        self.horizontalLayout_5.addWidget(self.qPushButton_submit)
        self.qPushButton_quit = QtWidgets.QPushButton(parent=qDialog_search_lyric)
        self.qPushButton_quit.setObjectName("qPushButton_quit")
        self.horizontalLayout_5.addWidget(self.qPushButton_quit)
        self.verticalLayout.addLayout(self.horizontalLayout_5)

        self.retranslateUi(qDialog_search_lyric)
        QtCore.QMetaObject.connectSlotsByName(qDialog_search_lyric)

    def retranslateUi(self, qDialog_search_lyric):
        _translate = QtCore.QCoreApplication.translate
        qDialog_search_lyric.setWindowTitle(_translate("qDialog_search_lyric", "搜索歌词"))
        self.qComboBox_source.setItemText(0, _translate("qDialog_search_lyric", "网易云"))
        self.qComboBox_source.setItemText(1, _translate("qDialog_search_lyric", "LRCLIB"))
        self.qComboBox_source.setItemText(2, _translate("qDialog_search_lyric", "syncedlyrics"))
        self.qLineEdit.setPlaceholderText(_translate("qDialog_search_lyric", "输入关键词"))
        self.qPushButton_search.setText(_translate("qDialog_search_lyric", "搜索"))
        self.qPushButton_submit.setText(_translate("qDialog_search_lyric", "确定"))
        self.qPushButton_quit.setText(_translate("qDialog_search_lyric", "取消"))
